### ISSUE TITLE
关于Arouter 使用ksp 后，无法覆盖以前使用Kapt 编译的APP

### ISSUE THREAD

**Issue by akingyin1987** [JailedBird/ArouterKspCompiler#12]
复盖安装后 初始化 Aroute 直接报异常 LogisticsCenter.init

**Comment by JailedBird** [comment]
覆盖是指覆盖安装么？ 另外麻烦贴一下详细的错误信息；

理论上LogisticsCenter.init是用来Arouter初始化的；如果代码生成正确，应该是不会影响的；
```
    public synchronized static void init(Context context, ThreadPoolExecutor tpe) throws HandlerException {
        mContext = context;
        executor = tpe;

        try {
            long startInit = System.currentTimeMillis();
            //load by plugin first
            loadRouterMap();
            if (registerByPlugin) {
                logger.info(TAG, "Load router map by arouter-auto-register plugin.");
            } else {
                Set<String> routerMap;

                // It will rebuild router map every times when debuggable.
                if (ARouter.debuggable() || PackageUtils.isNewVersion(context)) {
```

```
    /**
     * arouter-auto-register plugin will generate code inside this method
     * call this method to register all Routers, Interceptors and Providers
     */
    private static void loadRouterMap() {
        registerByPlugin = false;
        // auto generate register code by gradle plugin: arouter-auto-register
        // looks like below:
        // registerRouteRoot(new ARouter..Root..modulejava());
        // registerRouteRoot(new ARouter..Root..modulekotlin());
    }
```

**Comment by akingyin1987** [comment]
之前用的kapt，现在用的ksp 但版本号没变，这种情况下就会出现以下错误
  Caused by: com.alibaba.android.arouter.exception.HandlerException: ARouter::ARouter init logistics center exception! [com.alibaba.android.arouter.routes.ARouter$$Providers$$app]
                                                                                                    	at com.alibaba.android.arouter.core.LogisticsCenter.init(SourceFile:429)
                                                                                                    	at com.alibaba.android.arouter.launcher._ARouter.o(SourceFile:8)
                                                                                                    	at com.alibaba.android.arouter.launcher.ARouter.init(SourceFile:16)
                                                                                                    	at com.zlcdgroup.mrmsei.BaseApp.onCreate(SourceFile:15)
                                                                                                    	at com.zlcdgroup.mrmsei.Hilt_App.onCreate(SourceFile:4)
                                                                                                    	at com.zlcdgroup.mrmsei.App.onCreate(SourceFile:1)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1225)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:8583)
                                                                                                    	at android.app.ActivityThread.access$2800(ActivityThread.java:311) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2889) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:117) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:293) 
                                                                                                    	at android.app.ActivityThread.loopProcess(ActivityThread.java:9934) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9923) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

**Comment by akingyin1987** [comment]
应该是要升级下版本号，重新把缓存重置下就可以了。我后面试下

**Comment by JailedBird** [comment]
> 应该是要升级下版本号，重新把缓存重置下就可以了。我后面试下

好的，有问题可以继续反馈哈
