### ISSUE TITLE
ARouter + KSP : KSErrorType cannot be cast to class java.lang.String

### ISSUE THREAD

**Issue by dannycx** [JailedBird/ArouterKspCompiler#20]
您好，我在ArouterKspCompiler:1.9.20-1.0.7和KSP版本1.9.20-1.0.14的多模块项目中遇到如下报错，编译失败
KSErrorType cannot be cast to class java.lang.String

java.lang.ClassCastException: class com.google.devtools.ksp.symbol.impl.kotlin.KSErrorType cannot be cast to class java.lang.String (com.google.devtools.ksp.symbol.impl.kotlin.KSErrorType is in unnamed module of loader java.net.URLClassLoader @3dafe7ad; java.lang.String is in module java.base of loader 'bootstrap')
	at jdk.proxy17/jdk.proxy17.$Proxy55.path(Unknown Source)
	at cn.jailedbird.arouter.ksp.compiler.entity.RouteMetaKsp.<init>(RouteMetaKsp.java:16)
	at cn.jailedbird.arouter.ksp.compiler.entity.RouteMetaKsp.build(RouteMetaKsp.java:28)

**Comment by JailedBird** [comment]
hello，可以在项目分支中创建一个复现case么

**Comment by nanyeweiwu** [comment]
使用Arouter 的provider时，出现上面的错误

**Comment by JailedBird** [comment]
无响应，关闭issue~
